### ISSUE TITLE
Action does not run on `arm64` runners

### ISSUE THREAD

**Issue by aschen-builder** [hashicorp-contrib/setup-packer#502]
When attempting to use the `hashicorp-contrib/setup-packer@v1` action with `arm64` runners, jobs fail with an HTTP error and the message "Error: Unsupported architecture: arm64".

Here's a full error message from the most recent run:

```
Run hashicorp-contrib/setup-packer@v1
  with:
    github-token: ***
    packer-version: latest

Error: Unsupported architecture: arm64
/home/runner/actions-runner/_work/_actions/hashicorp-contrib/setup-packer/v1/dist/index.js:6899
        const err = new HTTPError(response.message.statusCode);
                    ^

HTTPError: Unexpected HTTP response: 404
    at /home/runner/actions-runner/_work/_actions/hashicorp-contrib/setup-packer/v1/dist/index.js:6899:[2](https://github.com/***/***/actions/runs/***/job/***#step:4:2)1
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/actions-runner/_work/_actions/hashicorp-contrib/setup-packer/v1/dist/index.js:6800:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  httpStatusCode: [4](https://github.com/***/***/actions/runs/***/job/***#step:4:4)04
}
```

Here's the YAML for the workflow:

```
on: workflow_dispatch
name: Build Image
jobs:
  build:
    name: Build
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    defaults:
      run:
        working-directory: .
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Packer
        uses: hashicorp-contrib/setup-packer@v1
      - name: Setup Node
        uses: buildjet/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Build Dependencies
        run: xargs sudo apt-get install <depends.txt

      - name: Make Images
        run: mkdir deploy && make images
```
